name: Publish to NuGet

on:
  push:
    tags:
      - 'v*' # Triggers when a new tag starting with 'v' is pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # Adjust to your project's .NET version if needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Pack the project
        run: dotnet pack Idris.Umbraco.Folder.IconPicker.csproj --configuration Release --output .

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push Idris.Umbraco.Folder.IconPicker.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
