name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'  # Triggers only when a version tag (e.g., v1.0.0) is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Adjust this version to your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Publish artifact
        run: dotnet publish -c Release -o output

      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: PluginBuild
          path: output

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: PluginBuild

      - name: Create NuGet package
          working-directory: Idris.Umbraco.Folder.IconPicker
          run: dotnet pack -c Release --output ../nupkg


      - name: Save NuGet package
        uses: actions/upload-artifact@v3
        with:
          name: PluginPackage
          path: nupkg

  publish:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Download NuGet package
        uses: actions/download-artifact@v3
        with:
          name: PluginPackage

      - name: Push package to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  # Add your NuGet API key as a GitHub secret
        run: |
          dotnet nuget push "nupkg/*.nupkg" \
          --api-key $NUGET_API_KEY \
          --source https://api.nuget.org/v3/index.json
